### ISSUE TITLE
Renderer excepts with square images

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.OpenCV#55]
calculation of the imageID fails in case of square images, because -w + h always results in 0. ie there is no change from the initial 1/1 size to any other square size. 

therefore this else-if case is never hit:
https://github.com/vvvv/VL.OpenCV/blob/b8291d55867822261d48654d1dd46c1e10e28bcc/src/Renderer.cs#L145

and subsequently this line throws an exception:
https://github.com/vvvv/VL.OpenCV/blob/b8291d55867822261d48654d1dd46c1e10e28bcc/src/Renderer.cs#L152

**Comment by joreg** [comment]
see also #54

**Comment by ravazquez** [comment]
Fixed in commit 35e18de. Awaiting release.

**Comment by joreg** [comment]
@ravazquez it seems to me this code is still fishy: 
2 things:
- it checks for img==null and then in this exact case accesses img.Width. that should lead to an AccessViolation, right?
- then the computation of the imageId is still problematic, because it wouldn't detect a change when width and height are exchanged: example: 512 + 256 equals 256 + 512. therefore i believe you'd have to bit-combine the values or maybe simply make it a string?

what do you think?

**Comment by ravazquez** [comment]
@joreg 

- even though technically you are right, the call path that leads to this line prevents img from ever being null (CVImage constructor and RefreshIplImage call). I will remove this img == null check altogether since it is unnecessary here and to avoid further confusion
- I am not so familiar with bit-combine magic, I will just go for a string solution. While testing this it became evident that I would need to add some additional symbols to prevent for example a 1x11 image to end up with the same string as a 11x1 image. Not elegant but it will do.

**Comment by tebjan** [comment]
> * I am not so familiar with bit-combine magic, I will just go for a string solution.

using strings is unfortunately a very bad idea, especially if this is used for change checks every frame... the string operation is a few hundred times more expensive than bit operations and it will allocate memory on every call.

a very simple way to combine two numbers is to multiply one with a factor of 10s, so for example

`long sizeNumber = width * 100000 + height;`

this will put the number of the width in front of the number with the height...

similar with bit shifts would be

`long sizeNumber = (width << 16) | height;`

this just moves the bits of width 16 places up and then merges it with the height bits.

**Comment by ravazquez** [comment]
Thanks for the pointer and the explanation @tebjan, I will try to implement this ASAP
