### ISSUE TITLE
Crop bug on one channel image

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.OpenCV#9]
When cropping one channel image it becomes distorted (channels are messed up).
(I'm rendering it with Skia.) 
See the patch attached.

p.s. The workaround is to ConvertColor (GRAY > BRGA) after the Crop, which is not right, but maybe gives a hint on what is wrong.

[CropBug.zip](https://github.com/vvvv/VL.OpenCV/files/2567608/CropBug.zip)

**Comment by ravazquez** [comment]
After running some tests it looks like the issue is on the Skia FromImage node, if I render the result of Crop using a VL.OpenCV Renderer it displays properly, also if I output the result of the ToImage node used after the Crop to vvvv and use the UploadImage node to render the texture in vvvv it displays properly.

**Comment by ravazquez** [comment]
@azeno has fixed this on the VL.Skia end and is pushing the fix now.
